    engines:
      eslint:
        exclude_paths:
          - "node_modules/**"
          - ".next/**" 
          - ".swc/**"
          - "coverage/**"
          - ".giyhub/**"
          - "test/**"
          - "public/**"