# El archivo debe empezar obligatoriamente con esta línea.
---

# La sección 'engines' se usa para ACTIVAR o DESACTIVAR herramientas.
# Es como un interruptor general para cada motor de análisis.
engines:
  eslint:
    enabled: true
  stylelint:
    enabled: true
  # 'duplication' es el motor genérico para detectar código duplicado.
  # Se le puede pasar configuración directamente aquí.
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - typescript

# La sección 'tools' se usa para la CONFIGURACIÓN AVANZADA de una herramienta específica.
# Aquí le decimos a ESLint y Stylelint que usen nuestros archivos de configuración locales.
tools:
  eslint:
    # Le indica a la herramienta ESLint que use el archivo de configuración de nuestro proyecto.
    config_file: .eslintrc.json
  stylelint:
    # Le indica a la herramienta Stylelint que use el archivo de configuración de nuestro proyecto.
    config_file: .stylelintrc.json

# La sección 'exclude_paths' define rutas que serán IGNORADAS POR TODAS las herramientas.
# Es ideal para carpetas de dependencias, builds y otros archivos generados.
exclude_paths:
  - "node_modules/**/*"
  - ".next/**/*"
  - "build/**/*"
  - "dist/**/*"
  - "coverage/**/*"
  - "public/**/*"
  - "next-env.d.ts"
  - "*.config.js"
  - "*.setup.js"
  - "*.config.mjs"