name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Cambia si tu rama principal se llama diferente

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel --prod --token=${{ secrets.VERCEL_TOKEN }} \
                 --scope=${{ secrets.VERCEL_ORG_ID }} \
                 --confirm \
                 --yes \
                 --project=${{ secrets.VERCEL_PROJECT_ID }}
